export const UPDATE_IS_AUTHENTICATED = 'UPDATE_IS_AUTHENTICATED';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const UN_AUTH_USER  ='UN_AUTH_USER' ;
export const DELETE_ACCESS_TOKEN = 'DELETE_ACCESS_TOKEN';
export const CLEAR_USER_INFO = 'CLEAR_USER_INFO';
export const SESSION_EXPIRED = 'SESSION_EXPIRED';
